runtime: nodejs
vm: true

env_variables:
  # --REQUIRED--
  DATABASE_URI: mongodb://localhost:27017/dev
  APP_ID: desiAppId_s70g0Fadsfsfe3nkl3r1ljosdfGswefo
  MASTER_KEY: desiAppMasterKey_vggAGE973ru30FwEADFksjdf
  # --OPTIONAL--
  # FILE_KEY: <your-file-key>
  # PARSE_MOUNT: /parse
  # CLOUD_CODE_MAIN:  